Repository find-my-item/FMI-FE, pull requests merged in 2025-09, with the labels that each got.

#5 chore: 디자인 토큰 파일 추가
  src/tokens/tokens.json
Labels: 🧹 chore

#7 테스트 파일 제거
  src/TEST_FILES/Button.test.tsx
  src/TEST_FILES/Button.tsx
  src/TEST_FILES/sum.test.ts
  src/app/globals.css
  src/app/page.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  tests-examples/demo-todo-app.spec.ts
Labels: 🧹 chore

#27 chore: 디자인 토큰 수정 완료
  src/tokens/build/build-tokens.json
  src/tokens/build/tailwind.config.js
  src/tokens/sd-core.json
Labels: 🧹 chore

#28 main 최신화
  convert-tokens.js
  dist/css/variables.css
  generate-tailwind-from-tokens.js
  package-lock.json
  package.json
  src/app/globals.css
  src/dictionary.config.js
  src/tokens/build/build-tokens.json
  src/tokens/build/tailwind.config.js
  src/tokens/sd-core.json
  src/tokens/sd-dark.json
  src/tokens/sd-light.json
  src/tokens/sd-test.json
  src/tokens/sd-theme.json
  src/tokens/sd-tokens-config.js
  src/tokens/split-tokens.js
  src/tokens/tokens.json
  src/tokens/tokens.sd.json
  src/tokens/tw-tokens-config.js
  tailwind.config.ts
  tailwind.tokens.js
Labels: 🌿 main

#36 chore(tokens): sync from FMI-DS
  src/tokens/tailwind.config.js
Labels: design-tokens, 🤖 automated

#37 chore(tokens): sync from FMI-DS
  src/utils/tokens/tailwind.config.js
Labels: design-tokens, 🤖 automated

#41 Chromatic CI/CD 파이프라인 설정
  .github/workflows/chromatic.yml
  package-lock.json
  package.json
Labels: 🧹 chore

#42 공통 컴포넌트 생성
  package-lock.json
  package.json
  src/app/(route)/example/page.tsx
  src/app/ToastProviders.tsx
  src/app/components/common/Modal/ModalLayout.stories.tsx
  src/app/components/common/Modal/ModalLayout.tsx
  src/app/components/common/Toast/Toast.stories.tsx
  src/app/components/common/Toast/Toast.tsx
  src/app/components/common/index.ts
  src/app/context/ToastContext.tsx
  src/app/layout.tsx
  src/app/providers.tsx
  src/app/types/ToastTypes.ts
Labels: 🎨 style

#44 임시 PR 로그인 input 공통 컴포넌트 이슈
  package-lock.json
  package.json
  src/app/(auth)/AuthButton.tsx
  src/app/(auth)/components/AuthButton.tsx
  src/app/(auth)/components/AuthInput.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signUp/page.tsx
  src/app/(auth)/types/FormData.ts
Labels: ✨ feature

#46 workflows Chromatic 로직 수정
  .github/workflows/chromatic.yml
Labels: 🧹 chore

#50 공통 컴포넌트 생성
  src/app/layout.tsx
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Footer/Footer.stories.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Header/Hedaer.stories.tsx
  src/components/Header/SideBar.tsx
  src/components/Modal/ModalLayout.tsx
  src/components/index.ts
  src/icon/Hamburger.tsx
  src/utils/useOverlayHandlers.ts
Labels: 🎨 style

#51 공통 Icon 컴포넌트 생성 및 스토리북 세팅 수정
  .storybook/main.ts
  next.config.ts
  package-lock.json
  package.json
  src/assets/eye-open.svg
  src/assets/logo.svg
  src/assets/menu.svg
  src/assets/x-second.svg
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Footer/Footer.stories.tsx
  src/components/Header/Header.tsx
  src/components/Header/Hedaer.stories.tsx
  src/components/Header/SideBar.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/Icon.tsx
  src/components/Icon/index.ts
  src/components/Modal/ModalLayout.stories.tsx
  src/components/Tab/Tab.stories.tsx
  src/components/Toast/Toast.stories.tsx
  vitest.config.ts
  vitest.shims.d.ts
Labels: 🧹 chore

#60 버셀 액션 롤백
  .github/workflows/vercel.yml
Labels: 🧹 chore

#67 Icon size props 미적용 문제 수정 및 Prettier 설정 업데이트
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/task.md
  .github/pull_request_template.md
  .prettierrc
  .storybook/vitest.setup.ts
  jest.config.js
  next.config.ts
  package-lock.json
  package.json
  playwright.config.ts
  prettier.config.cjs
  src/app/(route)/(auth)/signUp/page.tsx
  src/app/(route)/example/page.tsx
  src/app/(route)/manual/_components/ManualItem.tsx
  src/app/(route)/manual/layout.tsx
  src/app/(route)/manual/page.tsx
  src/app/components/common/Input/Input.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/DetailHeader/DetailHeader.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
  src/components/Header/SideBar.tsx
  src/components/ManualPopup/ManualPopup.tsx
  src/components/Modal/ModalLayout.stories.tsx
  src/components/Modal/ModalLayout.tsx
  src/components/Toast/Toast.tsx
  src/providers/ToastProviders.tsx
Labels: 🐞 bug, 🧹 chore

#68 main 최신화 (#52)
  .github/pull_request_template.md
  .github/workflows/chromatic.yml
  .storybook/main.ts
  next.config.ts
  package-lock.json
  src/app/(auth)/AuthButton.tsx
  src/app/(auth)/components/AuthButton.tsx
  src/app/(auth)/components/AuthInput.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signUp/page.tsx
  src/app/(auth)/types/FormData.ts
  src/components/Header/Header.tsx
  src/icon/Hamburger.tsx
Labels: 🌿 main
