Repository find-my-item/FMI-FE, pull requests merged in 2025-10, with the labels that each got.

#81 Chromatic workflows 수정
  .github/workflows/chromatic.yml
Labels: 🐞 bug, 🧹 chore

#83 스토리북 세팅 수정
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
Labels: 🐞 bug, 🧹 chore

#85 스토리북 세팅 재재수정
  .storybook/main.ts
  .storybook/vitest.setup.ts
Labels: 🐞 bug, 🧹 chore

#87 스토리북 tsconfig.ts 파일 추가
  .github/workflows/chromatic.yml
  .storybook/tsconfig.json
Labels: 🐞 bug, 🧹 chore

#88 스토리북 세팅 수정
  .storybook/main.mjs
  .storybook/tsconfig.json
Labels: 🐞 bug, 🧹 chore

#77 공지사항/고객센터 기초 UI, 테스트
  jest.config.js
  package-lock.json
  package.json
  src/app/(route)/list/_components/ListItem/ListItem.tsx
  src/app/(route)/notice/[id]/page.tsx
  src/app/(route)/notice/_components/CommentList.tsx
  src/app/(route)/notice/_components/Customer.tsx
  src/app/(route)/notice/_components/CustomerList.tsx
  src/app/(route)/notice/_components/NoticeView.tsx
  src/app/(route)/notice/_components/PostDetail.tsx
  src/app/(route)/notice/_constant/commentListObject.ts
  src/app/(route)/notice/_constant/customerListObject.ts
  src/app/(route)/notice/_constant/noticeListObject.ts
  src/app/(route)/notice/_constant/noticeTab.ts
  src/app/(route)/notice/_test/CustomerDetail.test.tsx
  src/app/(route)/notice/_test/CustomerList.test.tsx
  src/app/(route)/notice/_test/NoticeDetail.test.tsx
  src/app/(route)/notice/_test/NoticeList.test.tsx
  src/app/(route)/notice/_types/noticeContainer.ts
  src/app/(route)/notice/customer/[id]/page.tsx
  src/app/(route)/notice/customer/inquiry-private/page.tsx
  src/app/(route)/notice/page.tsx
  src/components/Icon/Icon.tsx
  src/components/Tab/Tab.tsx
Labels: 🎨 style, ✅ test

#90 글쓰기 페이지 기초 UI 구현
  src/app/(route)/write/layout.tsx
  src/app/(route)/write/page.tsx
  src/assets/arrow-right.svg
  src/assets/camera.svg
  src/assets/location.svg
  src/components/Icon/index.ts
  src/components/RequiredText/RequiredText.stories.tsx
  src/components/RequiredText/RequiredText.tsx
  src/components/index.ts
Labels: 🎨 style

#94 상세페이지 기초 UI 구현
  next.config.ts
  src/app/(route)/list/[id]/_components/CommentForm/CommentForm.stories.tsx
  src/app/(route)/list/[id]/_components/CommentForm/CommentForm.tsx
  src/app/(route)/list/[id]/_components/PostDetail/PostDetail.stories.tsx
  src/app/(route)/list/[id]/_components/PostDetail/PostDetail.tsx
  src/app/(route)/list/[id]/_components/PostDetailHeader/PostDetailHeader.stories.tsx
  src/app/(route)/list/[id]/_components/PostDetailHeader/PostDetailHeader.tsx
  src/app/(route)/list/[id]/_components/SimilarItem/SimilarItem.stories.tsx
  src/app/(route)/list/[id]/_components/SimilarItem/SimilarItem.tsx
  src/app/(route)/list/[id]/_components/SimilarItemsSection/SimilarItemsSection.stories.tsx
  src/app/(route)/list/[id]/_components/SimilarItemsSection/SimilarItemsSection.tsx
  src/app/(route)/list/[id]/_components/index.ts
  src/app/(route)/list/[id]/page.tsx
  src/app/(route)/list/_constants/listItem.ts
  src/app/(route)/list/layout.tsx
  src/app/(route)/list/page.tsx
  src/app/(route)/notice/_components/CommentList.tsx
  src/app/(route)/write/layout.tsx
  src/app/globals.css
  src/assets/image.svg
  src/assets/profile-check.svg
  src/assets/send.svg
  src/components/Chip/Chip.stories.tsx
  src/components/Chip/Chip.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/index.ts
  src/components/Input/Input.stories.tsx
  src/components/ManualPopup/ManualPopup.tsx
  src/components/RequiredText/RequiredText.tsx
  src/components/Tab/Tab.tsx
  src/components/index.ts
  src/icon/Hamburger.tsx
Labels: 🎨 style, 🖌️ UI/UX

#98 스토리북 세팅 수정 및 테스트
  package.json
Labels: 🐞 bug, 🧹 chore
